version: "3.9"

services: 
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:3000"
    # Enviroments variables project wide 
    environment:
      - DB_HOST=db
      - POSTRGES_DB=devdb
      - POSTRGES_USER=devuser
      - POSTGRES_PASSWORD=password
    # APP wont start unless database is up firstly
    depends_on:
      - db
    
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTRGES_DB=devdb
      - POSTRGES_USER=devuser
      - POSTGRES_PASSWORD=password


volumes:
  dev-db-data: